name: Deploy Microfrontends

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [host, shop, admin]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Check if service was modified
        id: changes
        run: |
          git fetch origin main --depth=1
          if git diff --quiet origin/main -- services/${{ matrix.service }}; then
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: env.skip != 'true'
        run: npm install

      - name: Build
        if: env.skip != 'true'
        run: npm run build --workspace=services/${{ matrix.service }}

      - name: Deploy to Onrender
        if: env.skip != 'true'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_URL_${{ matrix.service }} }}
