name: Deploy Microfrontends

on:
  push:
    branches:
      - main
  paths:
    - 'services/host/**'
    - 'services/shop/**'
    - 'services/admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [host, shop, admin]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --workspace=services/${{ matrix.service }}

      - name: Deploy to Onrender
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_URL_${{ matrix.service }} }}
